// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhtTBoeemEOzPiyp0fGMYHGiEhRtNqr6U',
    appId: '1:231795136694:web:a4064c6ec507694bf7ae17',
    messagingSenderId: '231795136694',
    projectId: 'radiomd-a3070',
    authDomain: 'radiomd-a3070.firebaseapp.com',
    storageBucket: 'radiomd-a3070.firebasestorage.app',
    measurementId: 'G-N5HND57KJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC51i6uRv17GDB2VbEbHOnhdHcXhJBgz18',
    appId: '1:231795136694:android:bf2c36111f511e7bf7ae17',
    messagingSenderId: '231795136694',
    projectId: 'radiomd-a3070',
    storageBucket: 'radiomd-a3070.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB739P4-sUVDb2usXN6TaZg26sSFi1zy8U',
    appId: '1:231795136694:ios:c445093df1ebf971f7ae17',
    messagingSenderId: '231795136694',
    projectId: 'radiomd-a3070',
    storageBucket: 'radiomd-a3070.firebasestorage.app',
    iosBundleId: 'com.example.radiomd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB739P4-sUVDb2usXN6TaZg26sSFi1zy8U',
    appId: '1:231795136694:ios:c445093df1ebf971f7ae17',
    messagingSenderId: '231795136694',
    projectId: 'radiomd-a3070',
    storageBucket: 'radiomd-a3070.firebasestorage.app',
    iosBundleId: 'com.example.radiomd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhtTBoeemEOzPiyp0fGMYHGiEhRtNqr6U',
    appId: '1:231795136694:web:f1574154f87ccfc3f7ae17',
    messagingSenderId: '231795136694',
    projectId: 'radiomd-a3070',
    authDomain: 'radiomd-a3070.firebaseapp.com',
    storageBucket: 'radiomd-a3070.firebasestorage.app',
    measurementId: 'G-LQSC1C48LW',
  );
}
